In [1]:
pip install dotenv

Collecting dotenv
  Downloading dotenv-0.9.9-py2.py3-none-any.whl.metadata (279 bytes)
Requirement already satisfied: python-dotenv in c:\users\giovanni.esposito\appdata\local\anaconda3\lib\site-packages (from dotenv) (1.1.0)
Downloading dotenv-0.9.9-py2.py3-none-any.whl (1.9 kB)
Installing collected packages: dotenv
Successfully installed dotenv-0.9.9
Note: you may need to restart the kernel to use updated packages.

In [3]:
import os
import dotenv

# la funzione load_dotenv legge il file .env e ne mette il contenuto
# nelle variabili d'ambiente del sistema operativo
dotenv.load_dotenv(dotenv_path=".env", override=True)

# tramite la libreria os ("operating system") leggiamo le variabili
# d'ambiente, e trasferiamo il contenuto in delle variabili Python
username = os.getenv("username")
password = os.getenv("password")
hostname = os.getenv("hostname")
database = os.getenv("database")

# controlliamo che sia andato tutto bene stampando a video le variabili
print(username, password, hostname, database)

studente_dapt Ep1c0d3!!D4t4**4n4lys1s epicode-data-pt-MySQL.cvetyjye2qbl.eu-central-1.rds.amazonaws.com AdventureWorksDW

In [4]:
pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.3-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.3-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.3
Note: you may need to restart the kernel to use updated packages.

In [86]:
# importiamo le variabili con le credenziali con il codice precedente, e
# poi:

import pymysql

# creiamo la variabile "connection" che gestisce la connessione a database
connection = pymysql.connect(
    host=hostname,
    user=username,
    password=password,
    database=database,
    cursorclass=pymysql.cursors.DictCursor
)

In [87]:
import pandas as pd

cursor = connection.cursor()
query = "SELECT * FROM dimproduct;"
cursor.execute(query)
result = cursor.fetchall()
dimproduct = pd.DataFrame(result)

# Quanti dati ci sono in totale ? 
# Si può vedere già dall'output ovvero 606 rows × 36 columns. Oppure 
print( dimproduct.shape ) 
print(dimproduct)

# Quali sono i metadati ? 
print ( dimproduct.info() )

# Stampiamo il primo elemento e l'ultimo, e 5 elementi a caso
dimproduct.head(1)
dimproduct.tail(1)
dimproduct.sample(5)

# I colori disponibili 
colori = dimproduct["Color"].unique()

for colore in colori:
    print(colore)

# Quanto pesano in media prodotti ? Il più leggero, il più pesante

dimproduct["Weight"].mean()
dimproduct["Weight"].min()
dimproduct["Weight"].max()

# Quanti prodotti pesano più di 100
filtro100 = dimproduct["Weight"] > 100
prodotti100 = dimproduct[filtro100]
prodotti100["ProductKey"].count()

# Quanto costano in media i prodotti
dimproduct["DealerPrice"].mean()

# Quali sono i quartili dei prezzi. Dopo alcune imprecazioni ho notato che DealerPrice conteneva stringhe 'object'
dimproduct["DealerPrice"] = pd.to_numeric(dimproduct["DealerPrice"])
dimproduct["DealerPrice"].describe()

# Prezzo medio prodotti di colore blu
colors = dimproduct.groupby("Color")
colors.get_group("Blue")["DealerPrice"].mean() #oppure

filtroblu = dimproduct["Color"] == "Blue"
dimproduct[filtroblu]["DealerPrice"].mean()

# Prezzo medio prodotti di colore rosso o nero
filtroRN = ( (dimproduct["Color"] == "Blue") | (dimproduct["Color"] == "Black") )
dimproduct[filtroRN]["DealerPrice"].mean() #oppure

dimproduct[dimproduct["Color"].isin(["Blue", "Black"])]["DealerPrice"].mean()

# Prezzo massimo per i prodotti di taglia 42 e peso oltre i 10 kg
filtroTP = ( (dimproduct["Size"] == "42") & (dimproduct["Weight"] > 10) )
dimproduct[filtroTP]["DealerPrice"].max()

# nome e costo per i prodotti di taglia 42 e peso oltre i 10 kg e colore argento
filtroTPC = ( (dimproduct["Size"] == "42") & (dimproduct["Weight"] > 10) & (dimproduct["Color"] == "Silver") )
colonne = ["EnglishProductName", "StandardCost"]
dimproduct[filtroTPC].loc[:,colonne]

# visualizzare standard cost e dealer price ultimi 20 elementi del dataset
dimproduct.loc[:,colonne].tail(20) # si può osservare che lo standard cost di un prodotto tendenzialmente non varia in funzione della taglia. Fa eccezione la categoria "Bottom Bracket", in cui il costo cambia tra le varianti.

(606, 36)
     ProductKey ProductAlternateKey  ProductSubcategoryKey  \
0             1             AR-5381                    NaN
1             2             BA-8327                    NaN
2             3             BE-2349                    NaN
3             4             BE-2908                    NaN
4             5             BL-2036                    NaN
..          ...                 ...                    ...
601         602             BB-8107                    5.0
602         603             BB-9108                    5.0
603         604          BK-R19B-44                    2.0
604         605          BK-R19B-48                    2.0
605         606          BK-R19B-52                    2.0

    WeightUnitMeasureCode SizeUnitMeasureCode     EnglishProductName  \
0                    None                None        Adjustable Race
1                    None                None           Bearing Ball
2                    None                None        BB Ball Bearing
3                    None                None  Headset Ball Bearings
4                    None                None                  Blade
..                    ...                 ...                    ...
601                     G                None      ML Bottom Bracket
602                     G                None      HL Bottom Bracket
603                    LB                  CM     Road-750 Black, 44
604                    LB                  CM     Road-750 Black, 48
605                    LB                  CM     Road-750 Black, 52

            SpanishProductName           FrenchProductName StandardCost  \
0                                                                  None
1                                                                  None
2                                                                  None
3                                                                  None
4                                                                  None
..                         ...                         ...          ...
601         Eje de pedalier GM          Axe de pédalier ML      44.9500
602         Eje de pedalier GA          Axe de pédalier HL      53.9400
603  Carretera: 750, negra, 44  Vélo de route 750 noir, 44     343.6500
604  Carretera: 750, negra, 48  Vélo de route 750 noir, 48     343.6500
605  Carretera: 750, negra, 52  Vélo de route 750 noir, 52     343.6500

     FinishedGoodsFlag  ...                 ChineseDescription  \
0                    0  ...                               None
1                    0  ...                               None
2                    0  ...                               None
3                    0  ...                               None
4                    0  ...                               None
..                 ...  ...                                ...
601                  1  ...                      铝合金车圈；大直径脚蹬轴。
602                  1  ...                         铝合金车圈和空心轴。
603                  1  ...  入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。
604                  1  ...  入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。
605                  1  ...  入门级成人自行车；确保越野旅行或公路骑乘的舒适。快拆式车毂和轮缘。

                                     ArabicDescription  \
0                                                 None
1                                                 None
2                                                 None
3                                                 None
4                                                 None
..                                                 ...
601  فناجين من سبيكة الألومنيوم؛ ذات محور دوران كبي...
602             فناجين من سبيكة الألومنيوم ومحور أجوف.
603  إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...
604  إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...
605  إنها دراجة مناسبة للمبتدئين من البالغين؛ فهي ت...

                                     HebrewDescription  \
0                                                 None
1                                                 None
2                                                 None
3                                                 None
4                                                 None
..                                                 ...
601           כיסויים מסגסוגת אלומיניום; ציר רחב-קוטר.
602               כיסויים מסגסוגת אלומיניום וציר חלול.
603  אופני מבוגרים למתחילים; מציעים רכיבה נוחה "מחו...
604  אופני מבוגרים למתחילים; מציעים רכיבה נוחה "מחו...
605  אופני מבוגרים למתחילים; מציעים רכיבה נוחה "מחו...

                                       ThaiDescription  \
0                                                 None
1                                                 None
2                                                 None
3                                                 None
4                                                 None
..                                                 ...
601              ดุมอลูมิเนียมอัลลอยด์ แกนเพลาขนาดใหญ่
602                   ดุมอลูมิเนียมอัลลอยด์และเพลากลวง
603  จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...
604  จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...
605  จักรยานระดับเริ่มต้นสำหรับผู้ใหญ่ ให้ความสบายใ...

                                     GermanDescription  \
0                                                 None
1                                                 None
2                                                 None
3                                                 None
4                                                 None
..                                                 ...
601  Außenringe aus Aluminiumlegierung; Radachse mi...
602  Außenringe aus Aluminiumlegierung und hohle Ac...
603  Ein Erwachsenenrad für Einsteiger; bietet Komf...
604  Ein Erwachsenenrad für Einsteiger; bietet Komf...
605  Ein Erwachsenenrad für Einsteiger; bietet Komf...

                                   JapaneseDescription  \
0                                                 None
1                                                 None
2                                                 None
3                                                 None
4                                                 None
..                                                 ...
601                               アルミニウム合金カップ、大径スピンドル。
602                              アルミニウム合金カップとホロー アクスル。
603  エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...
604  エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...
605  エントリー レベルに対応する、クロスカントリーにも街への買い物にも快適な、大人の自転車。ハブ...

                                    TurkishDescription  StartDate EndDate  \
0                                                 None 2003-07-01     NaT
1                                                 None 2003-07-01     NaT
2                                                 None 2003-07-01     NaT
3                                                 None 2003-07-01     NaT
4                                                 None 2003-07-01     NaT
..                                                 ...        ...     ...
601  Alüminyum alaşımı orta göbekler; geniş çaplı mil. 2013-07-01     NaT
602    Alüminyum alaşımı orta göbekler ve içi boş aks. 2013-07-01     NaT
603  "Başlangıç seviyesinde yetişkin bisikleti, kır... 2013-07-01     NaT
604  "Başlangıç seviyesinde yetişkin bisikleti, kır... 2013-07-01     NaT
605  "Başlangıç seviyesinde yetişkin bisikleti, kır... 2013-07-01     NaT

      Status
0    Current
1    Current
2    Current
3    Current
4    Current
..       ...
601  Current
602  Current
603  Current
604  Current
605  Current

[606 rows x 36 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 606 entries, 0 to 605
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             606 non-null    int64
 1   ProductAlternateKey    606 non-null    object
 2   ProductSubcategoryKey  397 non-null    float64
 3   WeightUnitMeasureCode  282 non-null    object
 4   SizeUnitMeasureCode    253 non-null    object
 5   EnglishProductName     606 non-null    object
 6   SpanishProductName     606 non-null    object
 7   FrenchProductName      606 non-null    object
 8   StandardCost           397 non-null    object
 9   FinishedGoodsFlag      606 non-null    int64
 10  Color                  606 non-null    object
 11  SafetyStockLevel       606 non-null    int64
 12  ReorderPoint           606 non-null    int64
 13  ListPrice              395 non-null    object
 14  Size                   299 non-null    object
 15  SizeRange              606 non-null    object
 16  Weight                 282 non-null    float64
 17  DaysToManufacture      606 non-null    int64
 18  ProductLine            380 non-null    object
 19  DealerPrice            395 non-null    object
 20  Class                  330 non-null    object
 21  Style                  301 non-null    object
 22  ModelName              397 non-null    object
 23  LargePhoto             606 non-null    object
 24  EnglishDescription     396 non-null    object
 25  FrenchDescription      396 non-null    object
 26  ChineseDescription     396 non-null    object
 27  ArabicDescription      396 non-null    object
 28  HebrewDescription      396 non-null    object
 29  ThaiDescription        396 non-null    object
 30  GermanDescription      396 non-null    object
 31  JapaneseDescription    396 non-null    object
 32  TurkishDescription     396 non-null    object
 33  StartDate              606 non-null    datetime64[ns]
 34  EndDate                200 non-null    datetime64[ns]
 35  Status                 406 non-null    object
dtypes: datetime64[ns](2), float64(2), int64(5), object(27)
memory usage: 170.6+ KB
None
NA
Black
Silver
Red
White
Blue
Multi
Yellow
Grey
Silver/Black

            EnglishProductName StandardCost
586  Mountain-400-W Silver, 38     419.7800
587  Mountain-400-W Silver, 40     419.7800
588  Mountain-400-W Silver, 42     419.7800
589  Mountain-400-W Silver, 46     419.7800
590    Mountain-500 Silver, 40     308.2200
591    Mountain-500 Silver, 42     308.2200
592    Mountain-500 Silver, 44     308.2200
593    Mountain-500 Silver, 48     308.2200
594    Mountain-500 Silver, 52     308.2200
595     Mountain-500 Black, 40     294.5800
596     Mountain-500 Black, 42     294.5800
597     Mountain-500 Black, 44     294.5800
598     Mountain-500 Black, 48     294.5800
599     Mountain-500 Black, 52     294.5800
600          LL Bottom Bracket      23.9700
601          ML Bottom Bracket      44.9500
602          HL Bottom Bracket      53.9400
603         Road-750 Black, 44     343.6500
604         Road-750 Black, 48     343.6500
605         Road-750 Black, 52     343.6500

In [20]:
path4 = "C:/Users/giovanni.esposito/Desktop/EPICODE/M3 PYTHON/datasets/altri_dataset/Mappa-dei-pub-circoli-locali-in-Italia.csv"
pub = pd.read_csv(path4, encoding = "latin1", sep = ";")

# attività longitudine 9-10 e latitudine 45-46
filtropub = (pub["Longitudine"] >= 9) & (pub["Longitudine"] <= 10) & (pub["Latitudine"] >= 45) & (pub["Latitudine"] <= 46)
pub[filtropub].count() # ci sono 306 attività in base al filtro, seppure 277 hanno il nome riportato

# attività in provincia di Vicenza
filtrovicenza = pub["Provincia"] == "VICENZA"
pub[filtrovicenza].count() # ci sono 73 attività in base al filtro, seppure 69 hanno il nome riportato

# attività lazialo-abbruzzesi 
filtroregione = (pub["Regione"] == "Lazio") | (pub["Regione"] == "Abruzzo") 
pub[filtroregione].count() # ci sono 337 attività in base al filtro, seppure 296 hanno il nome riportato

Comune                             337
Provincia                          337
Regione                            337
Nome                               296
Anno inserimento                   337
Data e ora inserimento             337
Identificatore in OpenStreetMap    337
Longitudine                        337
Latitudine                         337
dtype: int64

In [37]:
path2 = "C:/Users/giovanni.esposito/Desktop/EPICODE/M3 PYTHON/datasets/beginner_datasets/insurance.csv"
insurance = pd.read_csv(path2)

print("Le dimensioni del data set sono (righe/colonne): ", insurance.shape)
print("---")

insurance.head(10) #per avere un'anteprima di 10 righe

insurance.columns # per i nomi colonna

# finalmente usiamo groupby
insurance.groupby("region")["charges"].mean()  #differenze significative? senza fare nessuna analisi di distribuzione, probabilità ecc. diciamo solo che a west i premi assicurativi sono mediamente più bassi che a est.
insurance.groupby("smoker")["charges"].mean() #differenze significative? i fumatori pagano giustamente molto di più, in media un premio 3,8 volte maggiore
insurance.groupby("sex")["charges"].mean() #differenze significative? uomini con premi più alti in media dell'11%

# vediamo bmi
insurance["bmi"].describe()  # i descrittori statistici di bmi 

q1 = insurance["bmi"].quantile(0.25)
q2 = insurance["bmi"].quantile(0.50)
q3 = insurance["bmi"].quantile(0.75)
q4 = insurance["bmi"].max()

insurance["Qbmi"] = pd.cut( insurance["bmi"], bins=[0, q1, q2, q3, q4], labels=["Q1", "Q2", "Q3", "Q4"] )  # la funzione pd.cut me l'ha suggerita AI

insurance.groupby("Qbmi", observed=True)["charges"].describe() # e finally vediamo describe di charges per quartili di bmi

Le dimensioni del data set sono (righe/colonne):  (1338, 7)
---

,count,mean,std,min,25%,50%,75%,max
Qbmi,,,,,,,,
Q1,335.0,10360.662825,7698.736614,1121.8739,3802.147800,8582.30230,14466.987100,38245.59327
Q2,338.0,11407.831468,8941.216348,1131.5066,4667.914013,8659.37800,16777.619963,62592.87309
Q3,330.0,14358.173081,13368.823405,1135.9407,5046.491400,9750.55835,15499.528613,60021.39897
Q4,335.0,16987.936691,15621.508495,1141.4451,5646.341425,10736.87075,28114.592620,63770.42801

In [42]:
path0 = "C:/Users/giovanni.esposito/Desktop/EPICODE/M3 PYTHON/datasets/beginner_datasets/iris.csv"
iris = pd.read_csv(path0)

# media lunghezza petalo in tutto il dataset
iris["petal_length"].mean()

# media lunghezza petalo per specie Iris
iris.groupby("species")["petal_length"].mean()

# media, min, max della larghezza sepalo per specie Iris
iris.groupby("species")["sepal_width"].agg(["mean", "min", "max"])

species
Iris-setosa        3.418
Iris-versicolor    2.770
Iris-virginica     2.974
Name: sepal_width, dtype: float64

In [64]:
pathw = "C:/Users/giovanni.esposito/Desktop/EPICODE/M3 PYTHON/datasets/beginner_datasets/wine.csv"
vino = pd.read_csv(pathw)

vino.groupby("quality")["alcohol"].mean().sort_values()  # ordinando in modo crescente si vedono le differenze 
vino["alcohol"].mean()

# proviamo a esplicitare tutto in un output

media_per_qualita = vino.groupby("quality")["alcohol"].mean().sort_values()
media_totale = pd.Series({"Media_Totale": vino["alcohol"].mean()})
print(pd.concat([media_per_qualita, media_totale]))

# oppure 

media_per_qualita = vino.groupby("quality")["alcohol"].mean().sort_values()
media_totale = vino["alcohol"].mean()

confronto = pd.DataFrame(media_per_qualita)
confronto["vs_media"] = ""
for indice, riga in confronto.iterrows():
    if riga["alcohol"] > media_totale:
        confronto.loc[indice, "vs_media"] = ">media"
    else:
        confronto.loc[indice, "vs_media"] = "<media"
print(confronto)


# differenza alcol vini bianchi vs rossi
vino.groupby("type")["alcohol"].agg( ["min", "max","mean", "median", "std"] ) # differenze non troppo importanti, però chiaramente i bianchi hanno min e max più bassi, ma una media leggermente più alta così come maggiore varianza.
                                                                              # chissà che pessimi vini ci sono in questo dataset

# differenza per pH
vino.groupby("pH")["alcohol"].agg( ["min", "max","mean", "median", "std"] )  # cambia tutto perchè raggruppiamo per tanti valori diversi di pH. Comunque è abbastanza evidente che all'aumentare del pH aumenta la gradazione alcolica (c'è correlazione positiva)

# differenza per solfati
vino.groupby("sulphates")["alcohol"].agg( ["min", "max","mean", "median", "std"] ) # per i solfati c'è correlazione negativa

5                9.837783
4               10.180093
3               10.215000
6               10.587553
7               11.386006
8               11.678756
9               12.180000
Media_Totale    10.491801
dtype: float64
           alcohol vs_media
quality
5         9.837783   <media
4        10.180093   <media
3        10.215000   <media
6        10.587553   >media
7        11.386006   >media
8        11.678756   >media
9        12.180000   >media

            min   max       mean  median       std
sulphates
0.22       13.4  13.4  13.400000   13.40       NaN
0.23       12.2  12.2  12.200000   12.20       NaN
0.25       10.5  12.9  11.800000   11.90  1.183216
0.26       10.6  13.4  12.425000   12.85  1.322561
0.27       11.2  13.6  12.330769   12.70  0.969866
...         ...   ...        ...     ...       ...
1.61        9.5   9.5   9.500000    9.50       NaN
1.62        9.5   9.5   9.500000    9.50       NaN
1.95        9.9   9.9   9.900000    9.90  0.000000
1.98        9.8   9.8   9.800000    9.80       NaN
2.00        9.4   9.4   9.400000    9.40       NaN

[111 rows x 5 columns]

In [79]:
pathb = "C:/Users/giovanni.esposito/Desktop/EPICODE/M3 PYTHON/datasets/beginner_datasets/boston.csv"
boston = pd.read_csv(pathb)

# media in funzione del fiume carlone
boston.groupby("chas")["medv"].mean()  # non è che possiamo dirlo in base a variabile dummy, possiamo dire solo se cambia "stare vicino al fiume o no". In questo senso un pò varia in negativo.

# correlazione criminalità / prezzo abitazioni
boston.groupby("crim")["medv"].agg( ["min", "max","mean", "median", "std"] )  #per guardarlo a occhio
boston.loc[:, ["crim", "medv"] ].corr()  # anticipando la lezione successiva, correlazione negativa ma piuttosto blanda e poco solida

# numero medio stanze / rapporto alunni-insegnanti
boston.loc[:, ["rm", "ptratio", "medv" ] ].corr()   # numero medio di stanze, correlazione positiva con valore delle case...ci mancherebbe ! costa di più un quadrilocale o un bilocale ? 
                                                    # rapporto numero medio di stanze scarsa correlazione con ptratio, e già mi sembra alto ! correlazione spurissima

# numero medio stanze / rapporto alunni-insegnanti
boston.loc[:, ["rad", "age", "rm", "tax" ] ].corr() # scarsa correlazione tra accessibilità autostrade e media età abitazioni oppure numero di stanze. 
                                                    # correlazione positiva forte con aliquota imposta fondiaria. Forse l'aliquota tiene conto della posizione, tipo piano regolaratorio? Non conosco situazione USA, da verificare.

          rad       age        rm       tax
rad  1.000000  0.456022 -0.209847  0.910228
age  0.456022  1.000000 -0.240265  0.506456
rm  -0.209847 -0.240265  1.000000 -0.292048
tax  0.910228  0.506456 -0.292048  1.000000

In [82]:
employees_df = pd.DataFrame({
    'employee_id': [101, 102, 103, 104, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'department_id': [1, 2, 1, 2, 3]
})

departments_df = pd.DataFrame({
    'department_id': [1, 2, 3],
    'department_name': ['HR', 'IT', 'Finance'],
    'location': ['New York', 'San Francisco', 'Chicago']
})

# mergiamo con merge
merge = departments_df.merge(employees_df, on="department_id")
merge

# joiniamo con join
employees_df = employees_df.set_index("department_id")
departments_df = departments_df.set_index("department_id")
join = departments_df.join(employees_df)
join

# la differenza è che nella tabella con join il department_id è l'indice mentre nella tabella con merge abbiamo l'indice di default 0, 1, 2... 
# In aggiunta merge di default fa inner join, join di default fa left join

              department_name       location  employee_id     name
department_id
1                          HR       New York          101    Alice
1                          HR       New York          103  Charlie
2                          IT  San Francisco          102      Bob
2                          IT  San Francisco          104    David
3                     Finance        Chicago          105     Emma

In [103]:
cursor = connection.cursor()
query1 = "SELECT * FROM dimemployee;"
cursor.execute(query1)
result1 = cursor.fetchall()
dimemployee = pd.DataFrame(result1)

query2 = "SELECT * FROM dimemployeesalesterritory;"
cursor.execute(query2)
result2 = cursor.fetchall()
dimemployeesalesterritory = pd.DataFrame(result2)

join_empl = dimemployee.merge(dimemployeesalesterritory, on="EmployeeKey")
join_empl # restituisce 29 colonne, tutte quelle di dimemployee più l'unica colonna di territorykey

cursor = connection.cursor()
query3 = "SELECT * FROM dimsalesterritory;"
cursor.execute(query3)
result3 = cursor.fetchall()
dimsalesterritory = pd.DataFrame(result3)

joinsales = join_empl.merge(dimsalesterritory, on="SalesTerritoryKey")

joinsales.groupby(["SalesTerritoryCountry", "SalesTerritoryRegion"])["EmployeeKey"].count()

joinsales.groupby("SalesTerritoryCountry")["BaseRate"].mean().sort_values() # differenze apprezzabili per paese

SalesTerritoryCountry
United States     39.909309
Canada             41.59255
France             41.59255
Australia         47.764433
Germany           47.764433
United Kingdom    47.764433
Name: BaseRate, dtype: object